In [36]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [37]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [38]:
df.notnull().sum()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [39]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [40]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [41]:
X = df.drop("Outcome", axis="columns")
y = df.Outcome

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled[:3]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415]])

In [42]:

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, stratify=y, test_size=0.2, random_state=42
)

In [43]:
X_train.shape

(614, 8)

In [44]:
X_test.shape

(154, 8)

In [45]:
y_train.value_counts()

Outcome
0    400
1    214
Name: count, dtype: int64

In [46]:
y_test.value_counts()

Outcome
0    100
1     54
Name: count, dtype: int64

In [47]:
scores = cross_val_score(DecisionTreeClassifier(), X_train, y_train, cv=5)
scores

array([0.65853659, 0.69918699, 0.66666667, 0.65853659, 0.7295082 ])

In [48]:
scores.mean()

np.float64(0.6824870051979209)

In [49]:
bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(), n_estimators=100, max_samples=0.8, oob_score=True, random_state=42
)

bag_model.fit(X_train, y_train)
bag_model.oob_score_

0.749185667752443

In [50]:
bag_model.score(X_test, y_test)

0.7597402597402597

In [51]:
bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(), n_estimators=100, max_samples=0.8, oob_score=True, random_state=42
)

scores = cross_val_score(bag_model, X, y, cv=5)
scores

array([0.75974026, 0.74675325, 0.74675325, 0.83660131, 0.76470588])

In [52]:
scores.mean()

np.float64(0.7709107885578474)

In [53]:
score = cross_val_score(RandomForestClassifier(n_estimators=100), X_scaled, y, cv=5)
score.mean()

np.float64(0.7682879212290977)